import ContractNote_v2 from "../../components/ContractNote/contractNote_v2.jsx";

function ContractNoteV2Page({ data }) {
  // let dummydata = {
  //   sections: [
  //     {
  //       title: "SUBSCRIPTION",
  //       tableHeaders: [
  //         "Account Number",
  //         "Account Type",
  //         "Account Alias",
  //         "Kristal ID",
  //         "Name",
  //         "Fund Kristal",
  //         "Strategy Manager",
  //         "Note/Investment Size",
  //         "Settlement Currency",
  //         "Launch Date",
  //         "Execution Date",
  //         "Expiry Date",
  //         "Settlement Date",
  //         "Underlying Equity",
  //         "Underlying Equity Ticker",
  //         "Current Stock Price",
  //         "Strike Price",
  //         "Strike in % of Current",
  //         "Option Type",
  //         "Number of Shares",
  //         "Product Risk Rating",
  //         "Collateral Type",
  //         "Settlement Type",
  //         "Kristal Fees",
  //         "Portfolio Yield p.a. (after fees)",
  //         "Product Description",
  //       ],
  //       data: [
  //         "KSGP009664",
  //         "Kristal Pooled",
  //         "KSGO000236",
  //         "K11000000",
  //         "XXX XXXX XXXXX",
  //         "Elon ATVI 82.5 Sep 20",
  //         "Kristal Advisors (SG) Pte Ltd",
  //         "33000000",
  //         "USD",
  //         "07 Aug, 2020",
  //         "07 Aug, 2020",
  //         "18 Sep, 2020",
  //         "25 Sep, 2020",
  //         "ACTIVISION BLIZZARD INC",
  //         "ATVI US",
  //         "0.00",
  //         "82.50",
  //         "0.00",
  //         "PUT",
  //         "400000",
  //         "Very High",
  //         "Cash",
  //         "Physical Delivery upon Exercise",
  //         "0.00",
  //         "0.00",
  //         "The product constitutes a long position in cash or a fixed income instrument plus a sale of a PUT option on an equity asset underlying.",
  //       ],
  //       notes: [
  //         { key: "*", value: "Taxes are inclusive if any" },
  //         { key: "**", value: "Taxes are inclusive if any" },
  //       ],
  //     },
  //     {
  //       title: "Fixed Maturity ELON Trade Confirmation",
  //       tableHeaders: [
  //         "Strategy Manager",
  //         "Broker(s)",
  //         "Custodian(s)",
  //         "Bank",
  //         "Calculation Agent",
  //         "Client Account",
  //         "Type",
  //         "Available To",
  //         "Jurisdiction",
  //         "Form",
  //         "Launch Date",
  //         "Execution Date",
  //         "Expiry Date",
  //         "Settlement Date",
  //         "Business Day and Calendar Convention",
  //         "Adjusted Settlement Date",
  //         "Investment Amount",
  //         "Unit NAV Reporting Frequency",
  //         "Portfolio Yield p.a.",
  //         "Denomination",
  //         "Strategy Description",
  //         "Payoff Structure",
  //         "Fee / Costs / Charges",
  //         "Leverage",
  //         "Subscription Terms",
  //         "Unsubscription Terms",
  //         "Notice Period for Unsubscription",
  //       ],
  //       data: [
  //         "Kristal Advisors (SG) Pte Ltd",
  //         "Interactive Brokers",
  //         "Interactive Brokers",
  //         "DBS Singapore",
  //         "Kristal Advisors (SG) Pte Ltd",
  //         "K11000000",
  //         "Closed ended",
  //         "Accredited Investor / Institutional",
  //         "Singapore",
  //         "Pooled Account",
  //         "07 Aug, 2020",
  //         "07 Aug, 2020",
  //         "18 Sep, 2020",
  //         "25 Sep, 2020",
  //         "Following Business Day Convention of the calendar in which the ELON is denominated",
  //         "Issuer may choose to exercise the right to deliver the stock on a date prior to the Expiry Date. Such date is the Adjusted Expiry Date and the Date the ELON (FM) Kristal will settle prematurely is the Adjusted Settlement Date (2 Business Days after the Adjusted Expiry Date).",
  //         "USD 33,000.00",
  //         "Daily",
  //         "0.00",
  //         "USD",
  //         "The product constitutes a long position in a fixed income instrument and/or cash collateral plus a sale of a PUT option on an equity asset underlying. The coupon/return from the Fixed Income instrument plus the premium received by sale of the equity PUT less costs generate a fixed coupon for the investor. The Fixed Income instrument and the Equity option have a similar tenor / maturity / expiry. On maturity, subject to no early exercise of the sold option, the investor receives the proceeds from the fixed income interest plus option premium received less applicable fees, plus either the investment amount or shares of the equity underlying. The number of shares received are computed by dividing the investment amount by the strike price of the PUT.",
  //         "For each Unit invested, on Settlement Date, Client will receive: Fixed Coupon for the duration between Execution Settlement date and Maturity Date PLUS - If iShares High Yield Corporate Bond ETF (HYG) price > Strike Price on Expiry Date: Investment Amount OR - If Option Subscriber exercises their right to give delivery of stock, typically when iShares High Yield Corporate Bond ETF (HYG) price less than or equal  Strike Price on Expiry Date at Expiry Cut, 500 Shares or fractions thereof with the remainder in Cash OR On Adjusted Settlement Date, Adjusted Fixed Coupon PLUS - If Option Subscriber exercises their right to give delivery of stock, typically when iShares High Yield Corporate Bond ETF (HYG) price less than or equal Strike Price on Expiry Date at Expiry Cut, 500 Shares or fractions thereof with the remainder in Cash",
  //         "1% p.a. on Gross Asset Value at Inception; Act/360 day count All brokerage/custody/trading commissions and charges associated with the execution of this strategy will be absorbed by the Strategy Manager and covered through the Fees except for the event of an early termination by the Subscriber Subscriber to bear all transfer costs associated with fund transfer from/to their bank-account.",
  //         "Not Applicable",
  //         "Subscription period from and including Launch Date and up to but not including Execution Date. Client Account must be funded 2 calendar days prior to Execution Date.",
  //         "Unsubscription shall be addressed on a best effort basis. There is a high likelihood that in the event of an early redemption the client may receive only a fraction of his/her Investment Amount due to changes in the underlying mark to market.",
  //         "2 business days (as per Business Day Convention)",
  //       ],
  //     },
  //     {
  //       title:
  //         "Underlying Security Details - Fixed Income Instrument (For Bills/Notes)",
  //       tableHeaders: ["Collateral"],
  //       data: ["Cash Holding"],
  //       notes: [
  //         { key: "*", value: "Taxes are inclusive if any" },
  //         { key: "**", value: "Taxes are inclusive if any" },
  //       ],
  //     },
  //     {
  //       title: "Underlying Security Details - Fixed Option",
  //       tableHeaders: [
  //         "Underlying Asset",
  //         "Option Type",
  //         "Strike Price",
  //         "Option Expiry Style",
  //         "Number of Shares",
  //         "Option Expiry Date",
  //         "Settlement Date",
  //       ],
  //       data: [
  //         "ACTIVISION BLIZZARD INC",
  //         "PUT",
  //         "82.50",
  //         "American (Option Subscriber can choose to exercise the option and give delivery of the underlying stock on any date from Execution Date upto and inclusive of Expiry Date)",
  //         "400000",
  //         "18 Sep, 2020",
  //         "25 Sep, 2020",
  //       ],
  //     },
  //   ],
  //   disclaimer: [
  //     "1. The materials and data contained herein are provided to demonstrate how a Kristal works and are provided for information only. None of the materials and data shall be construed as: (i) an offer to purchase or sell securities; (ii) the solicitation of an offer to purchase or sell any securities; (iii) an offer to provide advice on securities; (iv) the provision of any advice on securities; (v) an offer to manage any asset; or (vi) the management of any asset in any jurisdiction. Kristal does not make any representation, undertaking, warranty, guarantee, or other assurance as to the timeliness, completeness, correctness, reliability, or accuracy of the materials and data herein. All opinions, forecasts or estimation expressed herein are subject to change without prior notice. No communication made through, or any information available on, this website or its related mobile application is or may be deemed to be financial, legal, tax, or accounting advice. You should not take, or omit to take, any action, in reliance on any part of the content available here without independent verification or advice. Kristal and its affiliates accept no liability or responsibility whatsoever for any direct or consequential loss and/or damages arising out of or in relation to any use of opinions, forecasts, materials and data contained herein or otherwise arising in connection therewith.",
  //     "2. Please note that Interactive Brokers, one of the Custodians and Brokers for this strategy, is an overseas broker not regulated by MAS.",
  //     "3. The Terms and Conditions of this indicative offer may be subject to changes without prior notice. A Subscriber agreeing to an subscription based on an indicative pricing range may receive a final term substantially different from the initial indicative pricing due to changes in the underlying market conditions.",
  //   ],
  //   riskDisclosure: [
  //     "Investment is subject to specific risks, some of which are summarized below:",
  //     "1. Overall investment risk: All investments in securities risk the loss of capital, even securities popularly perceived to be safe, such as money market funds or government issued securities. There may be increased risk due to the nature of the securities to be purchased and traded by the Fund and the investment techniques and strategies used to increase profits. While the Investment Manager will devote its best efforts to the management of the Fund's portfolio, it cannot give an assurance that the Fund",
  //   ],
  //   generatedOn: "Mon, 07 Dec 2020 13:40:37 UTC",
  // };
  return <ContractNote_v2 data={data} />;
}
export default ContractNoteV2Page;
