import GenerateReport from "../../components/Reports/generateReport.jsx";

function ReportsPage({ data }) {
  //pass dummydata to test on browser else pass from pros for API usage
  //   const data = {
  //     reportType: "Consolidated Report",
  //     period: "FEBRUARY 2022",
  //     notes: [
  //       "*Returns (Period) are measured using XIRR and are for the period of this report.",
  //     ],
  //     overview: {
  //       title: "Overview",
  //       tableHeaders: [
  //         "Kristal Id",
  //         "Name",
  //         "Portfolio Currency",
  //         "Portfolio Value (Period End)",
  //         "Portfolio Returns (Period)*",
  //         "Cash Transferred (Lifetime)",
  //         "Earnings (Lifetime)",
  //       ],
  //       data: [
  //         [
  //           "K19550000",
  //           "XXX XXXX XXXXX",
  //           "USD",
  //           "3,741,939.75",
  //           "-",
  //           "3,341,838.32",
  //           "400,101.43",
  //         ],
  //       ],
  //     },
  //     sections: [
  //       {
  //         title: "Portfolio Summary",
  //         tableHeaders: [
  //           "Account Type",
  //           "Sub-Account Number",
  //           "Currency",
  //           "Value (Period End)",
  //           "Returns (Period)*",
  //           "Cash Transferred (Lifetime)",
  //           "Earnings (Lifetime)",
  //           "Advisory Mode",
  //           "Execution Mode",
  //         ],
  //         notes: [
  //           "*Returns (Period) are measured using XIRR and are for the period of this report.",
  //         ],
  //         data: [
  //           [
  //             "Kristal Pooled",
  //             "KSGP000006",
  //             "USD",
  //             "3,449,173.20",
  //             "-",
  //             "2,929,010.75",
  //             "520,162.45",
  //             "Advised",
  //             "RM Assisted",
  //           ],
  //           [
  //             "Kristal Private Wealth",
  //             "U3382120",
  //             "USD",
  //             "156,070.41",
  //             "-",
  //             "139,548.62",
  //             "16,521.80",
  //             "Advised",
  //             "Click & Trade",
  //           ],
  //           [
  //             "Kristal Private Investment",
  //             "KSGP000512",
  //             "USD",
  //             "123,461.31",
  //             "-",
  //             "123,461.31",
  //             "0.00",
  //             "Advised",
  //             "RM Assisted",
  //           ],
  //           [
  //             "Saxo Bank",
  //             "29968SCM",
  //             "USD",
  //             "13,103.15",
  //             "-",
  //             "149,685.96",
  //             "-136,582.81",
  //             "Advised",
  //             "Click & Trade",
  //           ],
  //         ],
  //       },
  //       {
  //         title: "Kristals as of Period End",
  //         tableHeaders: [
  //           "Kristal Name",
  //           "Symbol",
  //           "Account no.",
  //           "Asset Class",
  //           "Quantity",
  //           "Currency",
  //           "Unit NAV",
  //           "NAV as of date",
  //           "Current Value",
  //           "Invested Amount",
  //           "Unrealized Returns (%)",
  //         ],
  //         notes: [
  //           "*Returns (Period) are measured using XIRR and are for the period of this report.",
  //         ],
  //         data: [
  //           [
  //             "FengHeAsia (USTE) Fund Ltd A (072021 Series)",
  //             "KSGP000006",
  //             "KYG3365C1096",
  //             "FUND",
  //             "0.06",
  //             "USD",
  //             "2.000000",
  //             "2022-02-28",
  //             "2,091.98",
  //             "2,000.00",
  //             "4.60",
  //           ],
  //           [
  //             "FengHeAsia (USTE) Fund Ltd A (072021 Series)",
  //             "KSGP000006",
  //             "KYG3365C1096",
  //             "FUND",
  //             "0.06",
  //             "USD",
  //             "2.000000",
  //             "2022-02-28",
  //             "2,091.98",
  //             "2,000.00",
  //             "4.60",
  //           ],
  //         ],
  //       },
  //       {
  //         title: "Orders (Period)",
  //         tableHeaders: [
  //           "Date",
  //           "Kristal Name",
  //           "Symbol",
  //           "Account",
  //           "Asset Class",
  //           "Trade Type",
  //           "Quantity",
  //           "Currency",
  //           "Unit Price",
  //           "Amount",
  //         ],
  //         notes: [
  //           "*Returns (Period) are measured using XIRR and are for the period of this report.",
  //         ],
  //         data: [
  //           [
  //             "2022-02-02",
  //             "Kotak India Fixed Income Fund",
  //             "LU0996347828",
  //             "FUND",
  //             "KSGP000006",
  //             "REDEEM",
  //             "3",
  //             "USD",
  //             "20.00",
  //             "60.00",
  //           ],
  //           [
  //             "2022-02-02",
  //             "Kotak India Fixed Income Fund",
  //             "LU0996347828",
  //             "FUND",
  //             "KSGP000006",
  //             "INVEST",
  //             "15,000",
  //             "USD",
  //             "20.00",
  //             "300,000.00",
  //           ],
  //         ],
  //       },
  //     ],
  //   };
  return <GenerateReport data={data} />;
}

export default ReportsPage;